# Generated by Django 3.1.2 on 2020-11-30 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('text_location', models.TextField()),
                ('picture', models.ImageField(max_length=1024, upload_to='photos')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_locator.location')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Phone'), ('E', 'Email'), ('TG', 'Telegram')], max_length=2)),
                ('method', models.CharField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectContacts', to='map_locator.project')),
            ],
        ),
    ]
