# Generated by Django 3.1.2 on 2020-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
