# Generated by Django 3.1.2 on 2020-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0002_auto_20201209_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
