# Generated by Django 3.1.2 on 2020-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0003_auto_20201209_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text_location',
            field=models.TextField(verbose_name='Описание местоположения'),
        ),
    ]
