# Generated by Django 3.1.2 on 2020-12-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0004_auto_20201209_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='y',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='x',
            new_name='longitude',
        ),
    ]
