# Generated by Django 3.1.2 on 2020-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0005_auto_20201209_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(choices=[('N', 'Organisator fullname'), ('ON', 'Organization Name'), ('P', 'Phone'), ('E', 'Email'), ('TG', 'Telegram')], max_length=2),
        ),
    ]
